openapi: 3.0.1
info:
  title: testCenter
  description: ''
  version: 1.0.0
tags:
  - name: doc
paths:
  '/indices/{indexName}/doc/{docId}':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
      - schema:
          type: string
        name: docId
        in: path
        required: true
    get:
      summary: 获取文档
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentModel'
      operationId: get-indices-indexName-doc
    put:
      summary: 更新文档
      operationId: put-indices-indexName-doc-docId
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
      tags:
        - doc
  '/indices/{indexName}':
    put:
      summary: 添加index
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      operationId: put-indices-indexName
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexModel'
        description: ''
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    get:
      summary: 获取index
      operationId: get-indices-indexName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      tags:
        - doc
    post:
      summary: 快速更新index，mapping关系的更新有可能出错，这时则需要调用recreate
      operationId: post-indices-indexName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexModel'
      tags:
        - doc
    delete:
      summary: 删除索引
      operationId: delete-indices-indexName
      responses:
        '200':
          description: OK
      tags:
        - doc
  '/indices/{indexName}/docs':
    post:
      summary: 批量上传文档
      operationId: post-indices-docs
      responses:
        '200':
          description: OK
      tags:
        - doc
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
  '/indices/{indexName}/search':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    get:
      summary: 查询文档
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentModel'
      operationId: get-indices-indexName-search
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: ''
  '/indices/{indexName}/recreate':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    post:
      summary: 重新创建index，用于mapping不兼容的修改
      tags:
        - doc
      operationId: post-indices-indexName-recreate
      responses:
        '200':
          description: OK
  /indices:
    get:
      summary: 获取所有的索引
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexModel'
      operationId: get-indices
  /collections:
    get:
      summary: 获取所有的数据集合
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexModel'
      operationId: get-collections
    parameters: []
  '/collections/{collectionName}':
    parameters:
      - schema:
          type: string
        name: collectionName
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - doc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      operationId: get-collections-collectionName
    delete:
      summary: ''
      operationId: delete-collections-collectionName
      responses:
        '200':
          description: OK
      tags:
        - doc
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    IndexModel:
      title: IndexModel
      x-stoplight:
        id: 66flccibutzbs
      type: object
      properties:
        name:
          type: string
        mapping:
          $ref: '#/components/schemas/MappingModel'
        desc:
          type: string
          x-stoplight:
            id: mu2ysot2256a2
        id:
          type: number
          x-stoplight:
            id: xfbfaigejpo10
        esIndexName:
          type: string
          x-stoplight:
            id: a1pp7lypvlpjq
        status:
          type: string
          x-stoplight:
            id: yh6h5yh9daoeq
    MappingModel:
      title: MappingModel
      x-stoplight:
        id: s5mk1of6r18rq
      type: object
      properties:
        properties:
          x-stoplight:
            id: apei92o9r75oy
          type: array
          items:
            $ref: '#/components/schemas/PropertyModel'
      required:
        - properties
    PropertyModel:
      title: PropertyModel
      x-stoplight:
        id: 4d2ab2cd56f6b
      type: object
      properties:
        name:
          type: string
          x-stoplight:
            id: 462fkkm8lxfeb
        type:
          type: string
          x-stoplight:
            id: le1ystos1tgx7
        alias:
          type: string
          x-stoplight:
            id: de9f7m7lzcnds
        restrict:
          $ref: '#/components/schemas/RestrictModel'
        docIdPart:
          type: boolean
          x-stoplight:
            id: getohjb4u8ja4
        required:
          type: boolean
          x-stoplight:
            id: liyd460xe0orq
      required:
        - name
        - type
        - docIdPart
        - required
    RestrictModel:
      title: RestrictModel
      x-stoplight:
        id: 2qmzg54hlunu9
      type: object
      properties:
        enumerateList:
          type: array
          x-stoplight:
            id: v284dhrsotrpe
          items:
            x-stoplight:
              id: odyr4x7945vnn
            type: string
        maxValue:
          type: number
          x-stoplight:
            id: ca3s8487rc08c
        minValue:
          type: number
          x-stoplight:
            id: 93mz2qfxaznok
    DocumentModel:
      title: DocumentModel
      x-stoplight:
        id: m6h1qe8bk1wib
      type: object
      properties:
        id:
          type: string
        index:
          type: string
          x-stoplight:
            id: x9n1sz6zw5xpm
        source:
          type: object
          x-stoplight:
            id: 0hgtnlqcxib8p
      required:
        - source
    ProblemModel:
      title: ProblemModel
      x-stoplight:
        id: e7v7lmhyy3pg2
      type: object
      properties:
        code:
          type: integer
          x-stoplight:
            id: n82ohjuwvvnfv
        msg:
          type: string
          x-stoplight:
            id: bailu9qhy9yu4
      required:
        - code
        - msg
  requestBodies: {}
