openapi: 3.0.1
info:
  title: testCenter
  description: ''
  version: 1.0.0
tags:
  - name: collection
  - name: index
paths:
  /collections:
    get:
      summary: 获取所有的数据集合
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CollectionModel'
      operationId: get-collections
      tags:
        - collection
    parameters: []
  '/collections/{collectionName}/docs':
    post:
      summary: 批量上传文档
      operationId: post-collections-docs
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
      tags:
        - collection
    parameters:
      - schema:
          type: string
        name: collectionName
        in: path
        required: true
  '/collections/{collectionName}':
    parameters:
      - schema:
          type: string
        name: collectionName
        in: path
        required: true
    get:
      summary: 获取Collection信息
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionModel'
      operationId: get-collections-collectionName
      tags:
        - collection
    delete:
      summary: 删除Collection
      operationId: delete-collections-collectionName
      responses:
        '200':
          description: OK
      tags:
        - collection
    put:
      summary: 创建Collection
      operationId: put-collections-collectionName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionModel'
      tags:
        - collection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectionModel'
  '/indices/{indexName}':
    put:
      summary: 添加index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      operationId: put-indices-indexName
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexModel'
        description: ''
      tags:
        - index
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    get:
      summary: 获取index
      operationId: get-indices-indexName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      tags:
        - index
    post:
      summary: 更新index
      operationId: post-indices-indexName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexModel'
      tags:
        - index
    delete:
      summary: 删除索引
      operationId: delete-indices-indexName
      responses:
        '200':
          description: OK
      tags:
        - index
      parameters:
        - schema:
            type: boolean
          in: query
          name: retainData
          description: 是否保留index对doc的修改
  '/indices/{indexName}/doc/{docId}':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
      - schema:
          type: string
        name: docId
        in: path
        required: true
    get:
      summary: 获取文档
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentModel'
      operationId: get-indices-indexName-doc
      tags:
        - index
    put:
      summary: 更新文档
      operationId: put-indices-indexName-doc-docId
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
      tags:
        - index
  '/indices/{indexName}/search':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    get:
      summary: 查询文档
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentModel'
      operationId: get-indices-indexName-search
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: ''
      tags:
        - index
  '/indices/{indexName}/active':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    post:
      summary: 激活Index，开始导入数据
      tags:
        - index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
          headers:
            job_id:
              schema:
                type: number
      operationId: post-indices-indexName-active
      description: ''
  '/indices/{indexName}/append':
    parameters:
      - schema:
          type: string
        name: indexName
        in: path
        required: true
    post:
      summary: 刷新并追加Index的数据
      tags:
        - index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexModel'
          headers:
            job_id:
              schema:
                type: number
      operationId: post-indices-indexName-append
  '/collections/{collectionName}/upload':
    parameters:
      - schema:
          type: string
        name: collectionName
        in: path
        required: true
    post:
      summary: 上传excel文件
      tags:
        - collection
      responses:
        '200':
          description: OK
          content: {}
      operationId: post-collections-collectionName-upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
  '/collections/{collectionName}/properties':
    parameters:
      - schema:
          type: string
        name: collectionName
        in: path
        required: true
    get:
      summary: 获取集合中记录所有的Property
      tags:
        - collection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PropertyModel'
      operationId: get-collections-collectionName-properties
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    IndexModel:
      title: IndexModel
      x-stoplight:
        id: 66flccibutzbs
      type: object
      properties:
        id:
          type: number
          x-stoplight:
            id: xfbfaigejpo10
        name:
          type: string
        collectionId:
          type: number
          x-stoplight:
            id: 1g3cl192mmmkg
        collectionName:
          type: string
          x-stoplight:
            id: jqzo99kfdn390
        desc:
          type: string
          x-stoplight:
            id: mu2ysot2256a2
        esIndexName:
          type: string
          x-stoplight:
            id: a1pp7lypvlpjq
        mapping:
          $ref: '#/components/schemas/MappingModel'
        status:
          type: string
          x-stoplight:
            id: yh6h5yh9daoeq
        autoAppendFromCollection:
          type: boolean
          x-stoplight:
            id: yx4h9b9h3bstj
      required:
        - name
        - autoAppendFromCollection
    MappingModel:
      title: MappingModel
      x-stoplight:
        id: s5mk1of6r18rq
      type: object
      properties:
        properties:
          x-stoplight:
            id: apei92o9r75oy
          type: array
          items:
            $ref: '#/components/schemas/PropertyModel'
      required:
        - properties
    PropertyModel:
      title: PropertyModel
      x-stoplight:
        id: 4d2ab2cd56f6b
      type: object
      properties:
        name:
          type: string
          x-stoplight:
            id: 462fkkm8lxfeb
        type:
          type: string
          x-stoplight:
            id: le1ystos1tgx7
          enum:
            - TEXT
            - DATE
            - NUMBER
            - BOOL
        alias:
          type: string
          x-stoplight:
            id: de9f7m7lzcnds
        restrict:
          $ref: '#/components/schemas/RestrictModel'
        docIdPart:
          type: boolean
          x-stoplight:
            id: getohjb4u8ja4
        required:
          type: boolean
          x-stoplight:
            id: liyd460xe0orq
        enable:
          type: boolean
          x-stoplight:
            id: 8m6rf2yo2c243
      required:
        - name
        - type
        - docIdPart
        - required
        - enable
    RestrictModel:
      title: RestrictModel
      x-stoplight:
        id: 2qmzg54hlunu9
      type: object
      properties:
        enumerateList:
          type: array
          x-stoplight:
            id: v284dhrsotrpe
          items:
            x-stoplight:
              id: odyr4x7945vnn
            type: string
        maxValue:
          type: number
          x-stoplight:
            id: ca3s8487rc08c
        minValue:
          type: number
          x-stoplight:
            id: 93mz2qfxaznok
    DocumentModel:
      title: DocumentModel
      x-stoplight:
        id: m6h1qe8bk1wib
      type: object
      properties:
        id:
          type: string
        index:
          type: string
          x-stoplight:
            id: x9n1sz6zw5xpm
        source:
          type: object
          x-stoplight:
            id: 0hgtnlqcxib8p
      required:
        - source
    ProblemModel:
      title: ProblemModel
      x-stoplight:
        id: e7v7lmhyy3pg2
      type: object
      properties:
        code:
          type: integer
          x-stoplight:
            id: n82ohjuwvvnfv
        msg:
          type: string
          x-stoplight:
            id: bailu9qhy9yu4
      required:
        - code
        - msg
    CollectionModel:
      title: CollectionModel
      x-stoplight:
        id: kaafy2bq68773
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          x-stoplight:
            id: qtbq4u861jdk7
        desc:
          type: string
          x-stoplight:
            id: gjr9zmme6sggx
        indices:
          type: array
          x-stoplight:
            id: uaajwtymh2ht2
          items:
            $ref: '#/components/schemas/IndexModel'
    JobModel:
      title: JobModel
      x-stoplight:
        id: koc77u64ymyeu
      type: object
      properties:
        id:
          type: number
        jobType:
          type: string
          x-stoplight:
            id: 2gjm16z00n29i
        jobStatus:
          type: string
          x-stoplight:
            id: m7pyc7ptd1s6i
        createAt:
          type: string
          x-stoplight:
            id: 65b5qidimycme
        updateAt:
          type: string
          x-stoplight:
            id: 3zn0dsn6xfsyz
        relateId:
          type: number
          x-stoplight:
            id: a8d8uryxoicv8
  requestBodies: {}
