spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/example?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver