spring:
  datasource:
    username: test
    password: 123456
    url: jdbc:postgresql://localhost:5432/example
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: http://localhost:9200

  rabbitmq:
    username: test
    password: test
    addresses: localhost:5672
    cache:
      connection:
        mode: channel

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG